### ISSUE TITLE
Does not work with postcss-bem-linter

### ISSUE THREAD

**Issue by ismay** [jeffjewiss/ember-cli-postcss#1]
When [postcss-bem-linter](https://github.com/necolas/postcss-bem-linter) and [postcss-log-warnings](https://github.com/davidtheclark/postcss-log-warnings) are installed (with postcss-log-warnings as the last object in the `Brocfile.js` configuration) the build is succesful, but no warnings are logged. Even though I'm importing a component that should result in a warning:

`app/styles/app.css`
```css
@import "./components/mycomponent.css";
```

`app/styles/components/mycomponent.css`
```css
/** @define MyComponent */

/* this should result in a warning: */
.WrongName {}
```

I'm using [postcss-import](https://github.com/postcss/postcss-import) to process `@import` rules, could it be that this is causing problems? I believe postcss-bem-linter expects separate files, with the `@define` rule on the first line (to trigger linting). Since ember-cli-postcss looks for `app.css` or `{app-name}.css`, and only processes that, could that be the reason linting isn't triggered?

If so, can this be fixed from ember-cli-postcss, and how?

**Comment by jeffjewiss** [comment]
Yeah, I couldn't get `postcss-bem-linter` working either and I'm using `postcss-import` to process `import` rules as well. I didn't realize that the `@define` had to be on the first line in a separate file, but that makes sense otherwise it would be difficult to tell when to stop linting for that component.

I'm not quite sure how to fix this just yet. I think my assumption to use `app.css` or `{app-name}.css` is too strict and was a naive first implementation to quickly get postcss working with ember-cli.

I'll need to think about this. I don't want to break how the addon currently works, but this definitely needs to be addressed.

**Comment by ismay** [comment]
> I'm not quite sure how to fix this just yet. I think my assumption to use app.css or {app-name}.css is too strict and was a naive first implementation to quickly get postcss working with ember-cli.

I'd say it is a good default (except for {app-name}.css, which ember-cli does not accept as an entry point for me, v0.2.3). 

Maybe it would make sense to allow for people to define their own array of entry points (with globbing), and default to all css in the `app/styles` folder, but not the folders below it (which are typically used for partials)? You could also allow people to explicitly define partials, and then default to folders below `app/styles`.

I'd almost think that you'd need different stages in the preprocessing for the types of uses that I've encountered):

1. process all css (and do stuff like linting all css with bem-linter)
2. process only the entry points and build

Maybe a key in the plugin array besides `module`, `options` could define whether the plugin is to be used for step 1 or step 2?

**Comment by ismay** [comment]
Or, you could fork this plugin to use the `postprocessTree` hook, and dedicate that exclusively to linting (since that's what the `postprocessTree` hook is for). That would separate the two use-cases cleanly.

**Comment by jeffjewiss** [comment]
I was able to solve this issue and get BEM linting to work by passing plugins to the `postcss-import` plugin, which will run the plugins on each file it imports. I think this is likely a preferable solution to using the `postprocessTree` hook as everything will run in one place.

The config can look something like this:

```
postcssOptions.plugins = [
  {
    module: require('postcss-import'),
      options: {
        glob: true,
        plugins: [
          require('postcss-nesting'),
          require('postcss-nested'),
          require('postcss-bem-linter'),
          require('postcss-browser-reporter'),
          require('postcss-reporter')({
            clearMessages: true,
            noPlugin: true
          })
        ]
      }
    },
    <more plugins>
  }
]
```

I'm going to close this issue since it's possible to setup linting. Please reopen the issue if you're unable to get this working in your projects.
