### ISSUE TITLE
Specify include and exclude on plugin level on filter

### ISSUE THREAD

**Issue by CodeDeFury** [jeffjewiss/ember-cli-postcss#184]
Hi, thanks for this addon.

Is it possible to specify include and exclude on the plugin level on filter?

Thanks !

**Comment by jeffjewiss** [comment]
Hi, could you please explain your use case with a bit more detail? Are you looking to have finer control over which Postcss plugins process each file by setting up include/exclude for each plugin?

**Comment by CodeDeFury** [comment]
> finer control over which Postcss plugins process each file by setting up include/exclude for each plugin

↑ yes

**Comment by jeffjewiss** [comment]
Unfortunately the addon doesn't currently support include/exclude at the plugin level. 

You could try specifying postcss plugins in the CSS files themselves by using the [postcss-use](https://github.com/postcss/postcss-use) plugin.

Otherwise, for a setup this custom, I'd recommend using [broccoli-postcss](https://github.com/jeffjewiss/broccoli-postcss) directly in your `ember-cli-build.js` as you'll likely need an instance created for each combination of postcss plugins you'd like to use.

**Comment by CodeDeFury** [comment]
@jeffjewiss, noted. I will try to solve it in my `ember-cli-build.js`.

Thanks for the suggestion.  🙇
