### ISSUE TITLE
Browser targets ignored

### ISSUE THREAD

**Issue by lewazo** [jeffjewiss/ember-cli-postcss#261]
It seems like this addon doesn't include the browsers list in `config/targets.js` to a plugin's browsers list anymore.

This is the options I use in my `ember-cli-build.js`

```
    postcssOptions: {
      compile: {
        extension: 'scss',
        enabled: true,
        parser: require('postcss-scss'),
        plugins: [
          {
            module: require('@csstools/postcss-sass'),
            options: {
              includePaths: [
                'node_modules/tachyons-sass',
              ],
            },
          },
          {
            module: require('autoprefixer'),
            options: {
              browsers: ['last 1 versions']
            }
          }
        ]
      }
    }
```

It works fine this way. But when I remove the `options.browsers` from the autoprefixer options, I expect it to use the list from the `config/targets.js` file but it doesn't. In fact, when the browsers list is not present on the autoprefixer options, nothing gets prefixed.

**Comment by jeffjewiss** [comment]
Sorry to hear you're running into this issue.

I was able to test this today on a personal project against `v4.0.0` of `ember-cli-postcss` and it's picking up the browser list from the `config/targets.js` with no problem and shows different output when changing the browsers.

Could you please share your `config/targets.js` file?

Is this a private project or one you could share?

Also, does autoprefixer work with the browser list if you move it to the `filter` step in `ember-cli-postcss` instead of the `compile` step? I'm just trying to isolate the issue and see if that matters.

Thanks!

**Comment by jeffjewiss** [comment]
Hi, wanted to check in on this. Have you been able to test this issue any further or create a reproduction of the problem? Thanks

**Comment by lewazo** [comment]
Hey, thanks for the help.

Sorry, I haven't had much time to work on my projet that uses `ember-cli-postcss`, but I did try moving it to filter and it didn't seem to work either.

I won't have much time in the next weeks or months, so I guess this can be closed.

**Comment by jeffjewiss** [comment]
Thanks for following up.

Sorry to hear that it wasn't working even with filter.

I realize you won't have time to work on the project, but do you mind sharing your `targets.js` file? I'd like to look further into this issue myself.

Please reopen the issue if you have time to work on the project in the future.

Thanks!
