### ISSUE TITLE
Very slow rebuilds

### ISSUE THREAD

**Issue by boris-petrov** [jeffjewiss/ember-cli-postcss#277]
Hi, thanks for the brilliant Ember plugin!

We migrated from `ember-cli-sass` to `ember-cli-postcss` with the following config:

```javascript
    ...
    postcssOptions: {
      compile: {
        extension: 'scss',
        enabled: true,
        parser: require('postcss-scss'),
        map: {
          annotation: true,
          inline: false,
        },
        plugins: [
          {
            module: require('@csstools/postcss-sass'),
            options: {
              includePaths: [...],
            },
          },
          { module: require('postcss-reporter') },
        ],
      },
      filter: {
        enabled: false,
        plugins: [
          {
            module: autoprefixer,
          },
        ],
      },
      ...
```

Note that the filter is disabled. This configuration should pretty much to exactly the same as `ember-cli-sass`. However, our rebuild times went up from milliseconds to 4+ seconds:

```
Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
PostcssCompiler (4)                           | 4369ms (1092 ms)
```

Any ideas why that might be? We tried playing with `includePaths` (which we've set to be *very* specific and with very few files in it) but it didn't help. How do we dig into that?

**Comment by jeffjewiss** [comment]
Sorry to hear that your rebuilds are running so slowly due to this addon.

I would expect the build times to be slightly slower with the above configuration, but not as slow as what you've outlined. Using the above configuration would create an AST of your CSS with Postcss, then parse it with the custom `postcss-scss` parser, then pass it on to `@csstools/postcss-sass` to process. So there is some overhead versus just using `ember-cli-sass`.

With that being said, I wouldn't expect rebuilds to take 4+ seconds, and I haven't seen that happen in any of the apps I've worked on with a similar configuration to the above.

Are you importing a lot of files in your stylesheets? Are any of these coming from `node_modules`? My suspicion is that the tree being parsed is very large due to some imports.

Also, do you mind sharing your goal in switching to Postcss? Are you looking to fully move away from using Sass and the above configuration is a step in that direction as you migrate, or are there features from both Sass and Postcss that you're looking to use?

Cheers

**Comment by boris-petrov** [comment]
Hi, last questions first - we're not trying to move away from Sass at all - we actually wanted to use autoprefixer at some point but `ember-cli-sass` and `ember-cli-autoprefixer` didn't play well together. Also, having something like `ember-cli-postcss` is perfect as it combines everything that we could possibly want in the future.

We are definitely not importing too many things. Our initial configuration for `ember-cli-sass` was:

```javascript
includePaths: ['app/webfont-svg', 'bower_components/bootswatch', 'tmp/iconfont'],
onlyIncluded: true,
```

I.e. we included a directory with SVG files in it (from which we generate a font), bootswatch themes and a generated SCSS file for that font. We also had a couple of includes in our SCSS like so:

```scss
@import 'node_modules/balloon-css/src/balloon';
```

Note the `onlyIncluded` option to `ember-cli-sass` which according to the documentation: `true/false whether to use only what is in app/styles and includePaths. This may helps with performance, particularly when using NPM linked modules`.

Then, our config changed (when we migrated to `ember-cli-postcss`) to:

```javascript
includePaths: ['node_modules', 'bower_components/bootswatch', 'app/webfont-svg', 'tmp/iconfont'],
```

Note that we included `node_modules` here because suddenly our imports from `node_modules` in our SCSS (the example from above) stopped working. We noticed the horrible performance and decided to include only the necessary things (pretty much what the `onlyIncluded` option did before):

```javascript
includePaths: ['node_modules/quill/dist', 'node_modules/balloon-css/src', 'bower_components/bootswatch', 'app/webfont-svg', 'tmp/iconfont'],
```

That's our current version. There's very few files in each of those directories.

Another very strange thing is that PostCSS seems to execute even when we don't change an SCSS file - e.g. when I change an HBS file or a CoffeeScript file - it again executes and takes 4 seconds. Any ideas why that also might be?

Where can I start debugging from? Where should I put console.logs to check what exactly takes long?

**Comment by jeffjewiss** [comment]
Thanks for the follow up details and clarification on your setup.

I was curious about your setup because one option would be to use `autoprefixer` as a plugin in the `filter` step with `ember-cli-postcss` to run after `ember-cli-sass`. The two should work well together and you can either whitelist or blacklist files with the include/exclude option.

After reading the reason for your setup, I see that this isn't ideal.

Have you tried commenting out the imports for the SVG files and font? I think it would be useful as a quick check to see if the slow builds are related to the parsing running on these files and trying to build a CSS AST from them mistakenly.

I'm not sure why it's executing when other files are changing. The file watching should be handled by `ember-cli`, which then triggers different parts of the build chain. My guess is that it could be related to having different file types in with the `.scss` files, but I haven't seen this behaviour on apps I've worked on.

Regarding debugging, could you please try creating an instrumentation visualization using https://github.com/ember-cli/broccoli-viz? You should be able to search the generated PDF for "CSS" and hopefully it will help determine which steps are the slowest.

I think this visualization will be a good first step to hopefully isolate the problem.

**Comment by boris-petrov** [comment]
Hi, thanks for the support!

I actually hadn't thought about using `ember-cli-sass` and only `autoprefixer` from `ember-cli-postcss` - perhaps I could try that. But I still think a "cleaner" way is to just use `ember-cli-postcss`.

I tried commenting out everything - i.e. `includePaths` is an empty array. Still the same performance. And still the same issue with PostCSS recompilation when I change a CoffeeScript file.

Here is a screenshot from Broccoli-viz after I update a CoffeeScript file:

![broccoli-viz](https://user-images.githubusercontent.com/278940/46402423-55537a00-c708-11e8-9322-0bf4abd5da89.png)

(the times are a bit less because we have normally 3 output CSS files (and hence 4 such "PostcssCompiler" boxes), here I've left only one output CSS file (and hence 2 boxes) - not sure why there is always one more box than output files)

As you can see, the compilation still happens and it's still slow. This is with the configuration from the first post just with `includePaths` being an empty array.

I'm not sure what more to look at this graph - is there something else you need to see from it? It's large and the rest is pretty much 0ms everywhere. Tell me what to do next. :)

**Comment by jeffjewiss** [comment]
Thanks for your patience with trying to get to the bottom of this.

If we can't figure out the cause of the slow builds, I would recommend the above mentioned approach of using `ember-cli-sass` and only `autoprefixer` from `ember-cli-postcss`. I agree that it would be much cleaner to use just `ember-cli-postcss` and that is the end goal here, but I'm not sure how long it will take to find the source of the issue.

Thanks for sharing the graph. I think that it confirms the issue isn't related to walking the node_modules directory or something similar. It looks like the slow builds are caused by either the parser or using node-sass as a postcss plugin.

As a next step, could you please try using the [postcss-cli](https://github.com/postcss/postcss-cli) on one of the files shown as a box in the graph above? You should be able to pass the same options used (parser, plugins, etc.). My hope here is to confirm that the times are roughly the same, which would mean the slowness is caused by either the `postcss-scss` parser or the `@csstools/postcss-sass` plugin, and not part of the ember-cli build chaing or something in the way `ember-cli-postcss` works. We can go from there.

Cheers

**Comment by boris-petrov** [comment]
Hi, thank *you* for the continued support! Sorry for the late reply, was busy this week with TypeScript issues. :)

`node-sass` is also used by `ember-cli-sass` so I'm not sure why would it be the problem. Anyway, here is what I did:

I installed `postcss-cli`, added a config file:

```javascript
module.exports = {
  extension: 'scss',
  enabled: true,
  parser: require('postcss-scss'),
  map: {
    annotation: true,
    inline: false,
  },
  plugins: [
    require('@csstools/postcss-sass')({ includePaths: ['node_modules/quill/dist', 'node_modules/balloon-css/src', 'bower_components/bootswatch', 'tmp/iconfont'] }),
    require('postcss-reporter'),
  ],
};
```

And I run this:

```sh
%  time postcss dist/assets/slate.css --dir asd
postcss dist/assets/slate.css --dir asd  2.10s user 0.09s system 151% cpu 1.453 total
```

"Slate" is one of the files we output. As you see it takes around 2 seconds. But I'm not sure I actually did what you wanted - did you want me to run `postcss-cli` on the *result* file after `ember-cli` runs or on the *input* files? I'm having some trouble running it on them - tell me if you actually meant that so I can sit down and figure it out.

Thanks again!

**Comment by jeffjewiss** [comment]
Thanks for the continued detailed updates!

I was hoping you could run `postcss-cli` with the config you mentioned on the input files. I wanted to compare the build/processing time for one of your input CSS files using `ember-cli` vs. `postcss-cli` to see if we could isolate the issue a bit further.

Regarding overall build performance, this [doc](https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md) might help a little. I think the debug section is of note, which gives options such as `DEBUG=* ember s`, which will provide much more verbose logging and may give some insight as to what's triggering the rebuild. Let me know what you find in that regard.

**Comment by boris-petrov** [comment]
Hi, sorry for the (even bigger) delay again!

Before I try playing more with `postcss-cli` I wanted to tell you what happens with `DEBUG=* ember server`.

First of all, we are also using `ember-component-css` and when I modify `app.ts` I see in the logs:

```
broccoli-sane-watcher [Funnel (ember-component-css grab files)#3059 -> WatchedDir#3060 -> /home/boris/code/project/frontend/app#3061] addWatchDir: (not added duplicate) /home/boris/code/project/frontend/app +1ms
```

I have no idea what this means but I'm not sure if it is normal to be executed when I modify a TypeScript file?

Much further down in the logs I see:

```
broccoli-funnel:Funnel: Packaged Ember CLI Internal Files build, { in: '0ms', linkedRoots: false, inputPath: '/home/boris/code/project/frontend/tmp/funnel-input_base_path-Pz63C5QB.tmp', destPath: '/home/boris/code/project/frontend/tmp/funnel-output_path-iqt5fccA.tmp/vendor/ember-cli' } +0ms
  broccoli-caching-writer:PostcssCompiler walking undefined +68ms
  broccoli-caching-writer:PostcssCompiler  cache eviction due to:
  broccoli-caching-writer:PostcssCompiler      - {file, /home/boris/code/project/frontend/tmp/postcss_compiler-input_base_path-zeyizyOo.tmp/frontend/app.ts, frontend/app.ts, 33188, 1220, 1540216921297}
  broccoli-caching-writer:PostcssCompiler      - {file, /home/boris/code/project/frontend/tmp/postcss_compiler-input_base_path-zeyizyOo.tmp/frontend/app.ts, frontend/app.ts, 33188, 1220, 1540216254448} +33ms
  broccoli-caching-writer:PostcssCompiler { stats: 0, files: 4686, inputPaths: [ '/home/boris/code/project/frontend/tmp/postcss_compiler-input_base_path-zeyizyOo.tmp' ] } +1ms
  broccoli-caching-writer:PostcssCompiler derive cacheKey in 34ms +0ms
  broccoli-caching-writer:PostcssCompiler purge output in 2ms +2ms
  broccoli-caching-writer:PostcssCompiler rebuilding cache in 785ms +785ms
```

This appears 4 times (because of the 4 outputs we have). Again, I'm not exactly sure what's going on but you can see that `rebuilding cache` takes ~800 ms. Does that help in any way?

**Comment by kevinansfield** [comment]
Hi 👋 Sorry for jumping in to an on-going thread but we've been running into a similar problem for quite a long time now. We don't use sass but do have a quite a few plugins and a lot of CSS imports, you can see our config here https://github.com/TryGhost/Ghost-Admin/blob/master/ember-cli-build.js#L147-L188 

Rebuilds typically take 8-10s with `PostcssCompiler` being the only listed "slow node" (2 build outputs, 4-5 seconds on postcss for each output). If this was only happening on CSS changes it wouldn't be too bad but similar to what @boris-petrov is seeing we also have slow postcss rebuilds for changes to JS and handlebars files.

I'd love to help debug this but I'm not too sure where to start 😄

**Comment by jeffjewiss** [comment]
Hey, thanks for adding that information. I really don't think it should be taking that long and it definitely shouldn't be triggered on any file change. I'd really like to fix this, but will likely need some help getting to the source of the issue.

Ghost might be easier to debug since it's not using ember-component-css and it's open source.

@kevinansfield could you please try a couple things? I'd to confirm that the issue is with the broccoli plugin and build process. Could you please try building Ghost Admin without the `cssnano` plugin and see if that makes any noticeable difference in the build time? Also, could you please try using `postcss-cli` to build your styles with all of the plugins and see how long it takes (maybe using `time`)? My thinking is that this could help determine if the issue is with Postcss and the combination of plugins being slow or if we can confirm it's something broccoli is doing, like maybe creating too many temporary files and digging too deep into node_modules.

Thanks!

**Comment by kevinansfield** [comment]
Taking the `cssnano` plugin out drops rebuild times considerably:

```
PostcssCompiler (2) (with cssnano)            | 5750ms (2875 ms)
PostcssCompiler (2) (without cssnano)         | 2666ms (1333 ms)
```

Build times are significantly slower when running with `postcss-cli`, maybe this is coming from the CLI startup and node module requires?

```
with cssnano...

❯ time postcss app/styles/app.css -o app-cli.css
postcss app/styles/app.css -o app-cli.css  6.46s user 0.41s system 162% cpu 4.229 total

❯ time postcss app/styles/app-dark.css -o app-dark-cli.css
postcss app/styles/app-dark.css -o app-dark-cli.css  6.48s user 0.39s system 158% cpu 4.331 total

without cssnano...

❯ time postcss app/styles/app.css -o app-cli.css          
postcss app/styles/app.css -o app-cli.css  3.41s user 0.52s system 127% cpu 3.078 total

❯ time postcss app/styles/app-dark.css -o app-dark-cli.css
postcss app/styles/app-dark.css -o app-dark-cli.css  3.09s user 0.29s system 152% cpu 2.210 total
```

For me the pain point is not so much that the build times can take a few seconds - I kind of expected that due to the amount of CSS and number of plugins that we have - but moreso that rebuilds are happening when non-CSS files change.

**Comment by jeffjewiss** [comment]
Thanks for running those tests.

I looked into this a bit and I'm not sure there's much I can do at the add-on level. I believe rebuilds being triggered for CSS processors by non-CSS file changes has been a long-time issue with `ember-cli` seen through issues like: https://github.com/ember-cli/ember-cli/issues/4647

I tried updating the caching options as outlined in: https://github.com/gabrielgrant/broccoli-less-single/issues/44 but still saw rebuilds when changing JS files. If you'd like to try it on Ghost I've pushed the branch: https://github.com/jeffjewiss/ember-cli-postcss/tree/fix-caching

I think this needs to be addressed within the `ember-cli` internals. The `PostcssCompiler` registers itself as a preprocessor with:

```js
  setupPreprocessorRegistry (type, registry) {
    let addon = this
    registry.add('css', new PostcssPlugin(addon))
  },
```

where the type is whether it's an add-on or app. So as far as I can tell there aren't any options to specify which files trigger a rebuild. I would think because it's being registered as a `'css'` processor that this should "just work". The only other place to specify file types is through the file extension, but this is set to: `this.ext = ['css', 'less', 'styl', 'scss', 'sass']`.

I know it doesn't solve your main issue, but the reason I asked about `cssnano` is that you could configure `ember-cli-postcss` with a different list of postcss plugins for `production` and only run `cssnano` when building for production. It doesn't address the main issue, but would save a few seconds with each rebuild.

**Comment by irminsul** [comment]
Using the `fix-caching` branch dramatically reduced the rebuild durations in my project.

With v4.2.1:

```
file changed styles/legacy/monitor.scss

Build successful (5682ms) – Serving on https://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
PostcssCompiler (1)                           | 4759ms
```

With `fix-caching`:

```
file changed styles/legacy/monitor.scss

Build successful (965ms) – Serving on https://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
Pod Templates (1)                             | 144ms               
BroccoliMergeTrees (34)                       | 121ms (3 ms)        
Package /assets/vendor.js (1)                 | 117ms               
StripBadReexports (2)                         | 62ms (31 ms)        
PostcssCompiler (1)                           | 51ms 
```

**Comment by samselikoff** [comment]
Same issue for me, I'm on a brand new Octane app with a simple config

![image](https://user-images.githubusercontent.com/2922250/76694550-83055800-664a-11ea-9361-b8590fc22365.png)

and every save in my project triggers postcss to rebuild

![image](https://user-images.githubusercontent.com/2922250/76694549-754fd280-664a-11ea-844f-63b1a669b613.png)

I'm not changing tailwind's config or anything so really this whole step should be skipped. I think this would be possible if the addon could cache more intelligently but not sure how without investigating more. Just wanted to add my comment here because I'm going to remove this and just use the CDN tailwind build because this is very slow.

**Comment by jeffjewiss** [comment]
Please try upgrading to `ember-cli-postcss` 6.0. Thanks to @ezpuzz there are improved defaults for caching.

Incremental builds are now much faster as postcss won't process the styles if js or hbs files are modified (this is configurable). I tested against Ghost-Admin and saw rebuild times for PostcssCompiler drop from ~2800ms to ~100ms.

**Comment by samselikoff** [comment]
Seems to have fixed the issue, thanks!

**Comment by samselikoff** [comment]
@jeffjewiss I saw the new `cacheInclude` options and the note about tailwind. I'm wondering if we still need to keep our `tailwind.config.js` file underneath the `/app` directory or if it's possible to keep it at the root of our project?

**Comment by jeffjewiss** [comment]
@samselikoff thanks for trying the new version and following up.

I think you should be able to move it to the root of the project. I just tested with a new/blank ember app and used `require('tailwindcss')('./tailwind.config.js')` as one of the postcss plugins and confirmed that changing one of the config values worked and made its way into the app.

As mentioned in the notes on caching: with the default settings you'll need to restart the ember server for changes to the tailwind config file to be picked up.

**Comment by kevinansfield** [comment]
@ezpuzz thank you! This makes a huge difference 😄

**Comment by boris-petrov** [comment]
@jeffjewiss, @ezpuzz - yep, now it's definitely fine, thank you everyone! :smile:

**Comment by samselikoff** [comment]
@jeffjewiss Having `tailwind.config.js` in the root does allow the `tailwindcss` plugin to pick it up, but changes to it aren't triggering rebuilds. If I stop and start the ember server again, the changes do take effect.

Here's my `postcssOptions`:

```js
postcssOptions: {
  compile: {
    enabled: true,
    plugins: [require("tailwindcss")],
    cacheExclude: [],
    cacheInclude: [/.*\.(css|scss)$/, /tailwind\.config\.js/]
  }
}
```

Any idea if this is possible?

**Comment by ezpuzz** [comment]
@samselikoff 

If you put your tailwind config in the `app/styles` directory it will trigger the build.

my config below:
```
    postcssOptions: {
      compile: {
        cacheInclude: [/\.css$/, /.*tailwind.*/],
        map: false,
        plugins: [
          {
            module: require("postcss-import"),
            options: {
              path: ["node_modules"],
            },
          },
          {
            module: require("tailwindcss"),
            options: {
              config: "./app/styles/tailwind.js",
            },
          },
        ],
      },
```

**Comment by samselikoff** [comment]
Yes it does, that's how I have it currently, but I was curious if we could it working with the `tailwind.config.js` file in the root of the project since that's the default place for it and the place that other tools (e.g. vscode tailwind intellisense) look for it.

Right now I have the file in app/styles and also in root, and the root version re-exports the app/styles version so intellisense works.

**Comment by jeffjewiss** [comment]
I don't think ember-cli sets up broccoli to watch files outside of the app folder by default. I haven't looked at broccoli.js in detail recently, but I think all the watcher stuff is setup internally and configured to create trees from the app folder.
