### ISSUE TITLE
Force rebuilds for file changes besides CSS

### ISSUE THREAD

**Issue by benmurden** [jeffjewiss/ember-cli-postcss#362]
In my case, I'm using [PurgeCSS](https://github.com/FullHuman/postcss-purgecss) with PostCSS, and would like to force a rebuild when `.hbs` files change.

I think it's probably because of this line https://github.com/jeffjewiss/ember-cli-postcss/blob/f86be75f1d4f0a4e2d0da50a84ac671a8aa2d2c8/index.js#L100

**Comment by jeffjewiss** [comment]
Yes, it's likely due to the line you mentioned. Unfortunately, a list of all of the available types isn't documented.

I should be able to update this hook to use something from the options to determine which types should trigger a build. I think maybe using the current behaviour as a default and then if an array of types is provided to check against those instead.

Out of curiosity, are you using PurgeCSS in environments other than production? What's the reason for doing so?

**Comment by benmurden** [comment]
This doc seems to mention at least a few.

https://ember-cli.com/api/classes/Addon.html#method_postprocessTree

The suggestion of an array option like

`processTrees: ['all', 'styles']`

would do it I think. Then I'd have something like

`processTrees: ['all', 'styles', 'template']`

to achieve what I was looking for.

PurgeCSS is not perfect, so you will still occasionally need to check output to see if it purged some classes that are actually used.

**Comment by jeffjewiss** [comment]
@benmurden could you please give the `process-trees-options` branch a try and see if that works as expected?

I was wondering about the environments you are using PurgeCSS with because I would personally only use it in the `production` environment when deploying an app since removing some unused CSS doesn't really help too much with development and so having templates trigger a live-reload of styles may not be necessary. You can specify different Postcss plugins to be run only in production by overriding the respective option in your `ember-cli-build.js`.

**Comment by benmurden** [comment]
@jeffjewiss In a perfect world I would use PurgeCSS only in the production environment, but it sadly gets it wrong - removing used CSS rules - frequently enough that I still need to check output for a number of changes. It gives me doubts about whether it's sensible to use it at all, given this, but I'll check the branch nonetheless.

**Comment by benmurden** [comment]
Had to make some modifications for it to work #364.
