### ISSUE TITLE
Less and other CSS processors support

### ISSUE THREAD

**Issue by ilkkao** [jeffjewiss/ember-cli-postcss#4]
It seems that out of the box `ember-cli-postcss` doesn't work together with `ember-cli-less`

Could it be documented (or fixed) how to setup `ember-cli-less` -> `ember-cli-postcss` pipeline?

For comparison, `ember-cli-less` -> `ember-cli-autoprefixer` combination works without any special configuration. You just need to install both of them separately.

**Comment by jeffjewiss** [comment]
Thanks for reporting this. I'm aware that this is an issue and trying to work on a solution.

The challenge is that `ember-cli-postcss` can do a lot more to your css and files than `ember-cli-autoprefixer` because of all of the plugins available to it. Right now `ember-cli-postcss` makes an assumption that you only want to process your main `app.css` file because the most common use case is that you will use imports.

This is what's causing the issue. However, if the plugin was updated to parse every file (as done with autoprefixer) and you used imports, you would likely get many duplicate files in your output.

Are you able to get `ember-cli-less` -> `ember-cli-cssnext` to work? If that pipeline works with your setup, I should be able to update this project to use a similar setup instead of the heavy handed assumption about `app.css`.

**Comment by lolmaus** [comment]
When I use ember-cli-postcss with ember-cli-sass, I receive this error:

> ENOENT: no such file or directory, open '/home/lolmaus/Code/loadimpact-assignment/tmp/tree_merger-tmp_dest_dir-SZomEydl.tmp/app/styles/app.css'

Adding this to my `ember-cli-build.js` resolved the issue:

    outputPaths: {
      app: {
        css: {
          'app': '/app/styles/app.css' // A hack to support ember-cli-postcss
        }
      }
    }

I believe this is a dirty hack. ember-cli-postcss should be able to work without it

**Comment by lolmaus** [comment]
Upd: started a new project, the above fix won't work anymore and there's no update.

Switching to `ember-cli-autoprefixer`.

**Comment by gabrielgrant** [comment]
Looks like this may be a (not so elegant) solution for SASS users, at least: https://www.npmjs.com/package/ember-cli-postcss-fixed

It seems to let you put the SASS compilation into the PostCSS processing pipeline, replacing ember-cli-sass. I imagine something similar could be hacked together for Less.

**Comment by jeffjewiss** [comment]
I've been working on a refactor of this addon, which should support using Postcss as a postprocessor, which in ember-cli terms means it should get run after other CSS processors. The branch, including an updated README, is here: https://github.com/postcss/postcss-import/blob/master/CHANGELOG.md#800---2015-01-27

Is anyone in this thread able to test this branch and running Postcss in combination with either Sass or Less?

Thanks!

**Comment by chrisjshull** [comment]
Gave the https://github.com/jeffjewiss/ember-cli-postcss/tree/refactor branch a test. 

Ran into an issue; looks like nothing is checking if the `compile.enabled` option is `false`.

**Comment by jeffjewiss** [comment]
Hey @chrisjshull, thanks for testing out the refactor branch!

I just added a check to the compile mode for the enabled option, merged the refactor branch into master, and published this as V3 of the addon.

I'm going to close this issue since you should now be able to use the filter mode of this addon with Less, but please let me know if you are still experiencing problems and I'll reopen the issue and address the problem.
