### ISSUE TITLE
Autoprefixer deprecation about browserslist

### ISSUE THREAD

**Issue by andreyfel** [jeffjewiss/ember-cli-postcss#424]
We've updated Autoprefixer to 9.6.0 and the build now gives a big red warning in the output:

```
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
```

Is this something we need to address in our project or we should fix it in `ember-cli-postcss`?

**Comment by jeffjewiss** [comment]
Since ember-cli supports browserlist via the targets.js file, ember-cli-postcss passes those options along to all postcss plugins with the goal of making using browser targets easy. So the warning is likely coming up due to this feature from the addon.

Are you currently configuring your browsers list via the config mentioned in that warning message or in the targets.js file? If the latter is the most common setup, I think it makes sense to update ember-cli-postcss to use the overrideBrowserslist key in the options.

**Comment by andreyfel** [comment]
I'm not adding any configs besides targets.js. So, yes, probably we should use overrideBrowserslist.

**Comment by jeffjewiss** [comment]
Okay thanks for confirming.

Could you please give this branch a try: https://github.com/jeffjewiss/ember-cli-postcss/tree/override-browserslist and let me know if the warning goes away and if your app still compiles as expected?

Thanks!

**Comment by andreyfel** [comment]
I've tried that branch and seems that it is working fine and fixing the original issue, I don't see those deprecations.

**Comment by jeffjewiss** [comment]
Okay great, thanks for your help in testing this!

**Comment by andreyfel** [comment]
@jeffjewiss Thanks for your help! Could you please make a new release containing this fix?

**Comment by jeffjewiss** [comment]
@andreyfel v4.2.1 should be out now. Cheers!
