### ISSUE TITLE
Example on README not working

### ISSUE THREAD

**Issue by samselikoff** [jeffjewiss/ember-cli-postcss#491]
Hi there – thanks for working on this addon!

I'm trying to follow the simple example in the README and having trouble getting it working in a brand new Ember app.

I copied this from the docs:

```js
const EmberApp = require('ember-cli/lib/broccoli/ember-app');
const autoprefixer = require('autoprefixer');

module.exports = function (defaults) {
  const app = new EmberApp(defaults, {
    postcssOptions: {
      compile: {
        enabled: false,
        browsers: ['last 3 versions'], // this will override config found in config/targets.js
      },
      filter: {
        enabled: true,
        plugins: [
          {
            module: autoprefixer,
            options: {
              browsers: ['last 2 versions'] // this will override the config, but just for this plugin
            }
          }
        ]
      }
    }
  });
  return app.toTree();
};
```

and `autoprefixer` doesn't seem to be working.

(Also, I was kind of confused by this example, since we disable the `compile` option but set its `browsers` property, and then enable the `filter` option. Could you elaborate on this?)

**Comment by samselikoff** [comment]
> When using Ember CLI >= 2.13.0, the browser targets configuration found in the file config/targets.js will be added to each plug-in’s options (as options.browsers). 

I think part of the problem was that this line isn't true anymore. On my new 3.13 app the autoprefixer plugin did respect a `browserlist` key in package.json (but not changes to config/targets.js). Maybe this line is just out of date.

Also, we're still having trouble `filter` to work at all. But `compile` does seem to be working.

**Comment by jeffjewiss** [comment]
Sorry to hear you're having issues setting this up.

If I remember correctly there was a deprecation in the browserlist plugin that changed the key it expects the array of browsers to be set on. What likely happened is that I didn't properly update all of the references to that key. I'm thinking it might be related to this PR: https://github.com/jeffjewiss/ember-cli-postcss/pull/425

Is this issue you're having with compile vs. filter setup separate from the autoprefixer issue?

**Comment by samselikoff** [comment]
Maybe as a first step we can look at this example from the readme: https://github.com/jeffjewiss/ember-cli-postcss#example

First question is, what is it trying to demonstrate? Why is `compile` disabled, and a browsers key specified? Why are we using `filter`? What's the use case for autoprefixer here?

**Comment by jeffjewiss** [comment]
Some users of this add-on wanted to use it in addition to other CSS processors. The addition of the filter step was to allow them to process the Ember app's CSS with Sass, Less, Stylus, etc. and then run postcss as a postprocess hook. The most common use case has been to run autoprefixer or similar plugins on all CSS files at the end of the build process. This step was named filter since a whitelist or blacklist can be applied.

The compile step is if you want to use postcss as your main CSS preprocessor, which will consume your app's app.css file.

You can choose to run either compile, filter or even both.

The browsers key is an outdated part of the Readme that I missed updating. It's a way of overriding the `target.js` file. That property was deprecated by autoprefixer in favour of `overrideBrowserslist`.

**Comment by samselikoff** [comment]
Gotcha. I think it wasn't clear from the "compile" vs. "filter" language.

In the example code, `compile` is disabled via `enabled: false`, but also has a config option set for `browsers`. Does that option do anything?

**Comment by jeffjewiss** [comment]
Sorry for missing your question.

Passing options to compile if `enabled: false` won't do anything as that step will be ignored. I've updated the config example to hopefully help clarify that.
