### ISSUE TITLE
Rebuild doesn't include changes in files with extension *.pcss

### ISSUE THREAD

**Issue by adc-mhaugen** [jeffjewiss/ember-cli-postcss#596]
I'm hoping to use the file extension `pcss` so my IDE can lint the files.  I've got it working with the following configuration:

```
        postcssOptions: {
            compile: {
                enabled: true,
                extension: 'pcss',
                includePaths: [ 'app/styles' ],
                plugins: [
                    PostCSSImport,
                    PostCSSPresetEnv({
                        features: {
                            'nesting-rules': true
                        }
                    })
                ]
            }
        }
```

If I change one of the `pcss` files it causes a rebuild, but the changes don't appear in the output.  Is this a supported configuration?

Thanks!

**Comment by jeffjewiss** [comment]
Thanks for reporting this. A new set of options was added to the `compile` step with version 6 related to caching and rebuilds.

The default is `cacheInclude: [/.*\.(css|scss|sass|less)$/]` so you'll need to add `cacheInclude: [/.*\.(css|pcss)$/]` as a property of the `compile` option in your configuration. This will tell Broccoli to check for `pcss` files on rebuilds. This setting was added so that editing `hbs` or `js` files doesn't cause Postcss to rebuild the styles.

Cheers

**Comment by jeffjewiss** [comment]
Hi, just wanted to check in and see if you got this working with the new configuration option. Thanks.

**Comment by adc-mhaugen** [comment]
Yes @jeffjewiss, I'm sorry, I should have responded.  It worked great.  Thanks for your help.
