### ISSUE TITLE
Embroider compatibility issue (filter)

### ISSUE THREAD

**Issue by 22a** [jeffjewiss/ember-cli-postcss#714]
I'm running into an issue where `ember-cli-postcss` filters aren't being run during app/addon builds.

From playing around with repo config and ember-cli-postcss internals locally I've managed to get pipelines working as expected using a very specific `compile` setup (instead of the `filter` we'd like to have the plugins run in) so I suspect the issue could be related to embroider's hook compatibility ([discord discussion](https://discord.com/channels/480462759797063690/568935504288940056/796762286113947648)), namely [`postprocessTree`](https://ember-cli.com/api/classes/addon#method_postprocessTree) used here: https://github.com/jeffjewiss/ember-cli-postcss/blob/30c324db5a1686e1657465e98be7783e1f93eb50/index.js#L100-L108

<br><br>

### Reproduction: https://github.com/22a/embroider-postcss-addon
The above repo is a freshly bootstrapped addon that just tries to bundle in TailwindCSS using their postcss "at-rule". To reproduce this filter issue locally, see the difference in output between `yarn start`vs.`yarn start:embroider`, `yarn build`vs.`yarn build:embroider`, etc.

**Comment by jeffjewiss** [comment]
Thanks for reporting this.

After reading through some of the docs and spec on embroider it looks like it doesn't currently implement any `postprocessTree` hooks. The spec has this listed as TBD and other addons seem to require patches to avoid relying on these hooks.

Is there another hook `ember-cli-postcss` can use when being built with embroider?

I'm not sure if this is a bug with this add-on since it seems like it may be due to embroider not implementing this hook. I'm open to adding support, but it's not clear to me what the path to doing so is.

Cheers

**Comment by GCheung55** [comment]
How about cross-posting to http://www.github.com/embroider-build/embroider?
