### ISSUE TITLE
`yarn outdated` is Confusing

### ISSUE THREAD

**Issue by jherdman** [jeffjewiss/ember-cli-postcss#773]
Hey Jeff!

Check this out:

```
# some shell session
$ yarn outdated

yarn outdated v1.22.5
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                      Current Wanted  Latest  Package Type           URL
ember-cli-postcss            7.0.0   7.0.2   6.0.2   devDependencies        https://github.com/jeffjewiss/ember-cli-postcss
```

Note that v6.0.2 is reported as the latest version. Can this be changed?

**Comment by jeffjewiss** [comment]
Hey James!

Thanks for reporting this. I back ported the Ember global removal change to 6.0.2 and didn't realize since it was published last that it would get tagged as the latest release even though it's a lower version number.

I've retagged 7.0.2 with the "latest" tag. Can you please let me know if that fixes the issue?

**Comment by jherdman** [comment]
Fixed! Many thanks!
