### ISSUE TITLE
How do I add postcss-nested to configuration?

### ISSUE THREAD

**Issue by allthesignals** [jeffjewiss/ember-cli-postcss#896]
Tailwind nesting docs show me this: https://tailwindcss.com/docs/using-with-preprocessors#nesting
<img width="379" alt="image" src="https://user-images.githubusercontent.com/5004319/171302810-853352a2-e221-41bb-872c-57be8828b9ea.png">

My ember-cli-build `postCssOptions` object looks like this:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/5004319/171302871-519cc2e6-b432-4ad5-b7b4-31fc07c68e3c.png">

How do I reconcile the two ways of adding postcss plugins? Is there documentation somewhere for this?

**Comment by jeffjewiss** [comment]
This add-on has a slightly different way of configuring plugins due to its age and the intent of sharing options with postcss and across plugins.

The way you've configured it in the screenshot is correct. The module/options config in ember-cli-postcss should result in the same config as shown in your screenshot for postcss.config.js.

If you want to add options to tailwindcss/nesting you could do:

```
{
  module: require('tailwindcss/nesting'),
  options: 'postcss-nested',
},
...
```

Whatever is set as the value for the options key will get passed to the plugin as its options argument.
