### ISSUE TITLE
`compile` throws error (with ember-cli-sass usage)

### ISSUE THREAD

**Issue by skddc** [jeffjewiss/ember-cli-postcss#92]
I'm trying to use this add-on in a project that's already using [`ember-cli-sass`](https://github.com/aexmachina/ember-cli-sass). I tried every combination of config for both this plugin and `outputPaths` that I could imagine, but I always get an exception for `app/styles/app.css` not existing in the `tmp` build dir. What does exist in there is exactly what I'd expect, i.e. `assets/myappname.css`.

If you're interested in looking at the exact code and error, you could look at branch in this PR: https://github.com/67P/hyperchannel/pull/116

**Comment by jeffjewiss** [comment]
Hi @skddc, thanks for reporting this. Unfortunately getting multiple css processors to work in the same project has been difficult (https://github.com/ember-cli/ember-cli/issues/2959, https://github.com/ember-cli/ember-cli/issues/6328), which is why I added the filter option to this add-on. 

The issue is that when you use `compile` this add-on is looking for `app/styles/app.css` in the tmp build dir (copied from your app's source), which doesn't exists since your project is using `ember-cli-sass` and the file is actually `app/styles/app.scss`. The file `assets/myappname.css` doesn't exist until it is written by `ember-cli-sass` when it finishes processing your sass files. This makes it challenging to use both sass and postcss because they're both attempting to use the same ember-cli build step hook.

**Proposed Solution**
I think you should be able to revert to using the configuration in this [commit](https://github.com/67P/hyperchannel/pull/116/commits/901a861e4c602e619c7a1c2da96b05f679c487cf).

Thanks for sharing the PR, it revealed in a reproducible form that there was a bug with the include/exclude settings. I've just published v3.3.0, could you please try using it with the filter configuration and let me know if that works with your project, for your use case?

Thanks!

**Comment by skddc** [comment]
Thank you so much! The new version and your proposed solution work perfectly fine.

**Comment by camnicklaus** [comment]
Thanks for this post! I'm a brand new ember user and was having this same problem, this solved it for me. FWIW I'm a bit of a novice coding and juuuust started learning ember so take this with a grain of salt but it might be worth adding a note to the readme regarding this fix
